import type { TranslationKey } from './en';

export const ar = {
  'common.back': 'رجوع',
  'common.send': 'إرسال',
  'common.continue': 'متابعة',
  'common.save': 'حفظ',
  'common.cancel': 'إلغاء',
  'common.retry': 'إعادة المحاولة',
  'common.loadError': 'تعذر تحميل البيانات',
  'common.noData': 'لا توجد بيانات',
  'common.points': '{{count}} نقطة',
  'common.or': 'أو',
  'common.appLogo': 'شعار التطبيق',
  'language.arabic': 'العربية',
  'language.english': 'الإنجليزية',
  'language.switchShort': 'EN',
  'language.switch': 'التبديل إلى الإنجليزية',
  'language.setting': 'اللغة: {{language}}',
  'tabs.home': 'الرئيسية',
  'tabs.retreat': 'الخلوة',
  'tabs.house': 'البيت',
  'tabs.profile': 'البروفايل',
  'tabs.more': 'المزيد',
  'fields.name': 'الاسم',
  'fields.birthDate': 'تاريخ الميلاد',
  'fields.stage': 'المرحلة',
  'fields.address': 'عنوان البيت',
  'fields.residence': 'محل الإقامة',
  'fields.phone': 'رقم الهاتف',
  'fields.whatsapp': 'رقم الواتس اب',
  'fields.school': 'المدرسة',
  'fields.classSaintName': 'اسم قديس الفصل',
  'fields.confessionFather': 'أب الاعتراف',
  'fields.confessionFatherOptional': 'أب الاعتراف (اختياري)',
  'fields.talents': 'المواهب',
  'fields.email': 'البريد الإلكتروني',
  'fields.password': 'كلمة المرور',
  'fields.confirmPassword': 'تأكيد كلمة المرور',
  'auth.signIn': 'تسجيل الدخول',
  'auth.welcomeBack': 'أهلاً، مرحباً بك مرة أخرى 👋',
  'auth.forgotPassword': 'هل نسيت كلمة المرور؟',
  'auth.faceLoginAccessibility': 'تسجيل الدخول بالوجه',
  'auth.fingerprintLoginAccessibility': 'تسجيل الدخول بالبصمة',
  'auth.noAccount': 'ليس لديك حساب؟',
  'auth.createAccount': 'إنشاء حساب',
  'auth.haveAccount': 'لديك حساب؟',
  'auth.personalData': 'البيانات الشخصية',
  'auth.basicData': 'البيانات الأساسية',
  'auth.faceGreeting': 'نسيت كلمة المرور؟ 👋',
  'auth.faceLogin': 'تسجيل الدخول بالوجه',
  'auth.fingerprintLogin': 'تسجيل الدخول بالبصمة',
  'auth.emailLogin': 'تسجيل الدخول بالبريد الإلكتروني',
  'auth.forgotTitle': 'نسيت كلمة المرور؟',
  'auth.forgotDescription':
    'أدخل بريدك الإلكتروني ليصلك كود التحقق لإعادة تعيين كلمة المرور.',
  'auth.newPasswordTitle': 'تسجيل كلمة مرور جديدة',
  'auth.currentPassword': 'كلمة المرور الحالية',
  'auth.newPassword': 'كلمة المرور الجديدة',
  'auth.confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
  'auth.changePassword': 'تغيير كلمة المرور',
  'auth.activationTitle': 'تأكيد تفعيل الحساب',
  'auth.registrationCodeTitle': 'كود التسجيل',
  'auth.activationDescription': 'أدخل كود تفعيل الحساب المرسل لك.',
  'auth.registrationCodeDescription':
    'أدخل كود التسجيل المرسل إلى بريدك الإلكتروني.',
  'auth.debugCode': 'كود بيئة الاختبار: {{code}}',
  'auth.codeCountdown': 'سيصلك الكود خلال {{seconds}} ثانية',
  'auth.noCode': 'لم تستقبل كود؟',
  'auth.resendCode': 'إعادة الإرسال',
  'auth.missingResetToken': 'لم يتم إصدار رمز إعادة تعيين كلمة المرور.',
  'auth.sessionStartFailed': 'تعذر بدء جلسة المستخدم.',
  'auth.otpAccessibility': 'كود مكون من 6 أرقام',
  'passwordRules.title': 'شروط كلمة المرور:',
  'passwordRules.length': '8 حروف',
  'passwordRules.number': 'رقم واحد',
  'passwordRules.uppercase': 'حرف كبير',
  'validation.required': '{{field}} مطلوب',
  'validation.emailRequired': 'البريد الإلكتروني مطلوب',
  'validation.emailInvalid': 'أدخل بريداً إلكترونياً صحيحاً',
  'validation.passwordMin': 'كلمة المرور يجب أن تتكون من 8 حروف على الأقل',
  'validation.passwordNumber': 'كلمة المرور يجب أن تحتوي على رقم',
  'validation.passwordUppercase': 'كلمة المرور يجب أن تحتوي على حرف كبير',
  'validation.passwordRequired': 'كلمة المرور مطلوبة',
  'validation.confirmPasswordRequired': 'تأكيد كلمة المرور مطلوب',
  'validation.passwordsMismatch': 'كلمتا المرور غير متطابقتين',
  'validation.currentPasswordRequired': 'كلمة المرور الحالية مطلوبة',
  'validation.otpInvalid': 'أدخل الكود المكون من 6 أرقام',
  'home.welcome': 'مرحباً بك',
  'home.upcomingEvents': 'الأحداث القادمة',
  'home.viewAll': 'عرض الكل',
  'home.dailyReading': 'قراءة اليوم',
  'home.questionBank': 'بنك الأسئلة',
  'home.knowMe': '🧠 تعرفيني؟ 🕊️',
  'home.sendAnswer': 'إرسال الإجابة',
  'home.sendAnswerError': 'تعذر إرسال الإجابة',
  'events.empty': 'لا توجد أحداث قادمة',
  'questions.aboutCategory': 'أسئلة عن {{category}}',
  'questions.emptyCategory': 'لا توجد أسئلة متاحة في هذا القسم',
  'questions.add': 'إضافة سؤال',
  'questions.proposed': 'السؤال المقترح',
  'questions.sent': 'تم إرسال السؤال المقترح',
  'questions.sendError': 'تعذر إرسال السؤال',
  'profile.title': 'البروفايل',
  'profile.edit': 'تعديل البيانات',
  'profile.saveError': 'تعذر حفظ البيانات',
  'profile.changePassword': 'تغيير كلمة المرور',
  'profile.points': 'النقاط 🪙',
  'profile.whatsappGroup': '🔗 اربط جروب الواتس اب',
  'profile.whatsappGroupError': 'رابط جروب الواتس اب',
  'more.title': 'القائمة',
  'more.suggestions': 'الاقتراحات',
  'more.reflection': 'الريفليكشن',
  'more.notifications': 'الإشعارات',
  'more.logout': 'تسجيل الخروج',
  'more.logoutPrompt': 'هل تريد تسجيل الخروج؟',
  'notifications.empty': 'لا توجد إشعارات',
  'retreat.shareReflection': 'شاركينا بتأملك',
  'retreat.sent': 'تم الإرسال',
  'retreat.sendError': 'تعذر الإرسال',
  'reflection.title': 'الريفليكشن',
  'reflection.lessonPoints': 'نقاط الدرس',
  'reflection.exercise': 'التدريب العملي للدرس',
  'reflection.completeError': 'تعذر حفظ الإكمال',
  'suggestions.general': 'اقتراحاتك لمدارس الأحد',
  'suggestions.lessons': 'اقتراحاتك لدروس مدارس الأحد',
  'suggestions.hymns': 'اقتراحاتك لترانيم مدارس الأحد',
  'suggestions.hymnRating': 'تقييم ترانيم مدارس الأحد',
  'suggestions.sendAs': 'إرسال المقترحات:',
  'suggestions.sent': 'تم إرسال المقترحات',
  'suggestions.sendError': 'تعذر إرسال المقترحات',
  'identity.anonymous': 'من مجهول',
  'identity.named': 'بالاسم',
  'chat.anonymous': 'مجهول الهوية',
  'chat.sendMessage': 'إرسال رسالة:',
  'chat.search': 'بحث عن المحادثات',
  'chat.block': 'حظر {{name}}',
  'chat.delete': 'إزالة المحادثة',
  'chat.empty': 'ابدأ محادثتك أو استفساراتك مع خادمات مدارس الأحد الآن',
  'chat.everyone': 'المحادثة مع\nالجميع',
  'chat.sendError': 'تعذر إرسال الرسالة',
  'chat.connected': 'متصل الآن',
  'chat.connecting': 'جار الاتصال…',
  'chat.reconnecting': 'جار إعادة الاتصال…',
  'chat.disconnected': 'غير متصل',
  'chat.connectionError': 'تعذر الاتصال — اضغط للمحاولة',
  'chat.sent': 'تم الإرسال',
  'chat.delivered': 'تم الاستلام',
  'chat.read': 'تمت القراءة',
  'errors.network': 'تعذر الوصول إلى الخادم. تحقق من الاتصال وحاول مرة أخرى.',
  'errors.unexpected': 'حدث خطأ غير متوقع. حاول مرة أخرى.',
  'errors.validation_error': 'بعض البيانات غير صحيحة. راجعها وحاول مرة أخرى.',
  'errors.authentication_required': 'سجل الدخول للمتابعة.',
  'errors.account_unavailable': 'هذا الحساب غير متاح.',
  'errors.email_already_registered': 'البريد الإلكتروني مسجل بالفعل.',
  'errors.verification_invalid': 'كود التحقق غير صحيح.',
  'errors.verification_expired': 'انتهت صلاحية كود التحقق.',
  'errors.verification_locked': 'عدد المحاولات غير الصحيحة كبير. حاول لاحقاً.',
  'errors.account_not_found': 'لم يتم العثور على الحساب.',
  'errors.invalid_credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
  'errors.account_disabled': 'هذا الحساب معطل.',
  'errors.account_not_verified': 'لم يتم تفعيل هذا الحساب.',
  'errors.current_password_invalid': 'كلمة المرور الحالية غير صحيحة.',
  'errors.invalid_token': 'جلستك غير صالحة. سجل الدخول مرة أخرى.',
  'errors.invalid_token_type': 'لا يمكن استخدام هذه الجلسة هنا.',
  'errors.refresh_token_revoked': 'انتهت جلستك. سجل الدخول مرة أخرى.',
  'errors.invalid_reset_token':
    'رابط إعادة تعيين كلمة المرور غير صالح أو منتهي.',
  'errors.category_not_found': 'لم يتم العثور على قسم الأسئلة.',
  'errors.question_not_found': 'لم يتم العثور على السؤال.',
  'errors.question_already_answered': 'تمت الإجابة عن هذا السؤال من قبل.',
  'errors.notification_not_found': 'لم يتم العثور على الإشعار.',
  'errors.invalid_activity': 'نشاط واحد أو أكثر غير متاح.',
  'errors.reflection_not_found': 'لم يتم العثور على درس الريفليكشن.',
  'errors.reflection_already_completed': 'تم إكمال هذا التدريب من قبل.',
  'errors.conversation_not_found': 'لم يتم العثور على المحادثة.',
  'errors.conversation_blocked': 'هذه المحادثة محظورة.',
  'errors.whatsapp_group_unavailable': 'رابط جروب الواتس اب غير متاح.',
  'errors.house_conversation_managed':
    'لا يمكن حظر محادثة البيت المشتركة أو إزالتها.',
  'errors.verification_delivery_unavailable':
    'خدمة إرسال بريد التحقق غير متاحة.',
  'errors.verification_delivery_failed':
    'تعذر إرسال بريد التحقق. حاول مرة أخرى.',
} satisfies Record<TranslationKey, string>;
