export const en = {
  'common.back': 'Back',
  'common.send': 'Send',
  'common.continue': 'Continue',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.retry': 'Try again',
  'common.loadError': 'Unable to load data',
  'common.noData': 'No data available',
  'common.points': '{{count}} points',
  'common.or': 'or',
  'common.appLogo': 'Application logo',
  'language.arabic': 'Arabic',
  'language.english': 'English',
  'language.switchShort': 'العربية',
  'language.switch': 'Switch to Arabic',
  'language.setting': 'Language: {{language}}',
  'tabs.home': 'Home',
  'tabs.retreat': 'Retreat',
  'tabs.house': 'House',
  'tabs.profile': 'Profile',
  'tabs.more': 'More',
  'fields.name': 'Name',
  'fields.birthDate': 'Date of birth',
  'fields.stage': 'Stage',
  'fields.address': 'Home address',
  'fields.residence': 'Residence',
  'fields.phone': 'Phone number',
  'fields.whatsapp': 'WhatsApp number',
  'fields.school': 'School',
  'fields.classSaintName': 'Class patron saint',
  'fields.confessionFather': 'Father of confession',
  'fields.confessionFatherOptional': 'Father of confession (optional)',
  'fields.talents': 'Talents',
  'fields.email': 'Email address',
  'fields.password': 'Password',
  'fields.confirmPassword': 'Confirm password',
  'auth.signIn': 'Sign in',
  'auth.welcomeBack': 'Hello, welcome back 👋',
  'auth.forgotPassword': 'Forgot your password?',
  'auth.faceLoginAccessibility': 'Sign in with face recognition',
  'auth.fingerprintLoginAccessibility': 'Sign in with fingerprint',
  'auth.noAccount': "Don't have an account?",
  'auth.createAccount': 'Create account',
  'auth.haveAccount': 'Already have an account?',
  'auth.personalData': 'Personal information',
  'auth.basicData': 'Account information',
  'auth.faceGreeting': 'Forgot your password? 👋',
  'auth.faceLogin': 'Sign in with Face ID',
  'auth.fingerprintLogin': 'Sign in with fingerprint',
  'auth.emailLogin': 'Sign in with email',
  'auth.forgotTitle': 'Forgot your password?',
  'auth.forgotDescription':
    'Enter your email address and we will send you a verification code to reset your password.',
  'auth.newPasswordTitle': 'Set a new password',
  'auth.currentPassword': 'Current password',
  'auth.newPassword': 'New password',
  'auth.confirmNewPassword': 'Confirm new password',
  'auth.changePassword': 'Change password',
  'auth.activationTitle': 'Confirm account activation',
  'auth.registrationCodeTitle': 'Verification code',
  'auth.activationDescription':
    'Enter the account activation code sent to you.',
  'auth.registrationCodeDescription':
    'Enter the verification code sent to your email address.',
  'auth.debugCode': 'Test environment code: {{code}}',
  'auth.codeCountdown': 'The code will arrive within {{seconds}} seconds',
  'auth.noCode': "Didn't receive a code?",
  'auth.resendCode': 'Resend',
  'auth.missingResetToken': 'A password reset token was not issued.',
  'auth.sessionStartFailed': 'Unable to start the user session.',
  'auth.otpAccessibility': 'Six-digit verification code',
  'passwordRules.title': 'Password requirements:',
  'passwordRules.length': '8 characters',
  'passwordRules.number': 'One number',
  'passwordRules.uppercase': 'One uppercase letter',
  'validation.required': '{{field}} is required',
  'validation.emailRequired': 'Email address is required',
  'validation.emailInvalid': 'Enter a valid email address',
  'validation.passwordMin': 'Password must contain at least 8 characters',
  'validation.passwordNumber': 'Password must contain a number',
  'validation.passwordUppercase': 'Password must contain an uppercase letter',
  'validation.passwordRequired': 'Password is required',
  'validation.confirmPasswordRequired': 'Password confirmation is required',
  'validation.passwordsMismatch': 'Passwords do not match',
  'validation.currentPasswordRequired': 'Current password is required',
  'validation.otpInvalid': 'Enter the six-digit verification code',
  'home.welcome': 'Welcome',
  'home.upcomingEvents': 'Upcoming events',
  'home.viewAll': 'View all',
  'home.dailyReading': 'Daily reading',
  'home.questionBank': 'Question bank',
  'home.knowMe': '🧠 Do you know me? 🕊️',
  'home.sendAnswer': 'Send answer',
  'home.sendAnswerError': 'Unable to send the answer',
  'events.empty': 'No upcoming events',
  'questions.aboutCategory': 'Questions about {{category}}',
  'questions.emptyCategory': 'No questions are available in this category',
  'questions.add': 'Add a question',
  'questions.proposed': 'Proposed question',
  'questions.sent': 'The proposed question was sent',
  'questions.sendError': 'Unable to send the question',
  'profile.title': 'Profile',
  'profile.edit': 'Edit profile',
  'profile.saveError': 'Unable to save your information',
  'profile.changePassword': 'Change password',
  'profile.points': 'Points 🪙',
  'profile.whatsappGroup': '🔗 Connect WhatsApp group',
  'profile.whatsappGroupError': 'WhatsApp group link',
  'more.title': 'Menu',
  'more.suggestions': 'Suggestions',
  'more.reflection': 'Reflection',
  'more.notifications': 'Notifications',
  'more.logout': 'Sign out',
  'more.logoutPrompt': 'Do you want to sign out?',
  'notifications.empty': 'No notifications',
  'retreat.shareReflection': 'Share your reflection',
  'retreat.sent': 'Sent successfully',
  'retreat.sendError': 'Unable to send',
  'reflection.title': 'Reflection',
  'reflection.lessonPoints': 'Lesson points',
  'reflection.exercise': 'Practical exercise',
  'reflection.completeError': 'Unable to save completion',
  'suggestions.general': 'Your Sunday School suggestions',
  'suggestions.lessons': 'Your Sunday School lesson suggestions',
  'suggestions.hymns': 'Your Sunday School hymn suggestions',
  'suggestions.hymnRating': 'Rate the Sunday School hymns',
  'suggestions.sendAs': 'Send suggestions as:',
  'suggestions.sent': 'Suggestions sent successfully',
  'suggestions.sendError': 'Unable to send suggestions',
  'identity.anonymous': 'Anonymous',
  'identity.named': 'With name',
  'chat.anonymous': 'Anonymous',
  'chat.sendMessage': 'Send a message:',
  'chat.search': 'Search conversations',
  'chat.block': 'Block {{name}}',
  'chat.delete': 'Remove conversation',
  'chat.empty': 'Start a conversation or ask your Sunday School servants now',
  'chat.everyone': 'Chat with\neveryone',
  'chat.sendError': 'Unable to send the message',
  'chat.connected': 'Online now',
  'chat.connecting': 'Connecting…',
  'chat.reconnecting': 'Reconnecting…',
  'chat.disconnected': 'Offline',
  'chat.connectionError': 'Unable to connect — tap to retry',
  'chat.sent': 'Sent',
  'chat.delivered': 'Delivered',
  'chat.read': 'Read',
  'errors.network':
    'Unable to reach the server. Check your connection and try again.',
  'errors.unexpected': 'An unexpected error occurred. Please try again.',
  'errors.validation_error':
    'Some information is invalid. Review it and try again.',
  'errors.authentication_required': 'Please sign in to continue.',
  'errors.account_unavailable': 'This account is unavailable.',
  'errors.email_already_registered':
    'This email address is already registered.',
  'errors.verification_invalid': 'The verification code is invalid.',
  'errors.verification_expired': 'The verification code has expired.',
  'errors.verification_locked': 'Too many invalid attempts. Try again later.',
  'errors.account_not_found': 'The account was not found.',
  'errors.invalid_credentials': 'Email or password is incorrect.',
  'errors.account_disabled': 'This account is disabled.',
  'errors.account_not_verified': 'This account is not verified.',
  'errors.current_password_invalid': 'Current password is incorrect.',
  'errors.invalid_token': 'Your session is invalid. Please sign in again.',
  'errors.invalid_token_type': 'This session cannot be used here.',
  'errors.refresh_token_revoked':
    'Your session has expired. Please sign in again.',
  'errors.invalid_reset_token':
    'The password reset link is invalid or expired.',
  'errors.category_not_found': 'The question category was not found.',
  'errors.question_not_found': 'The question was not found.',
  'errors.question_already_answered': 'This question was already answered.',
  'errors.notification_not_found': 'The notification was not found.',
  'errors.invalid_activity': 'One or more activities are unavailable.',
  'errors.reflection_not_found': 'The reflection lesson was not found.',
  'errors.reflection_already_completed': 'This exercise is already completed.',
  'errors.conversation_not_found': 'The conversation was not found.',
  'errors.conversation_blocked': 'This conversation is blocked.',
  'errors.whatsapp_group_unavailable':
    'The WhatsApp group link is unavailable.',
  'errors.house_conversation_managed':
    'The shared house conversation cannot be blocked or removed.',
  'errors.verification_delivery_unavailable':
    'Verification email delivery is unavailable.',
  'errors.verification_delivery_failed':
    'The verification email could not be delivered. Please try again.',
} as const;

export type TranslationKey = keyof typeof en;
